# Subtle SwayFX translucency and blur
blur enable
blur_xray disable
blur_passes 2
blur_radius 3
blur_noise 0.02
blur_brightness 1.0
blur_contrast 1.0
blur_saturation 1.0
for_window [app_id=".*"] opacity 0.96
for_window [class=".*"] opacity 0.96

layer_effects "waybar" {
    blur enable
    blur_xray enable
    blur_ignore_transparent enable
}
